[build]
  publish = "public" # Der Ordner, der nach dem Build die fertige Webseite enthält
  command = "npm run build"  # Dein Build-Befehl, z.B. für ein React-Projekt

[[redirects]]
  from = "/https://whiscasftw.github.io/LidiaWebseite123/"
  to = "/ornate-cuchufli-a48330.netlify.app/"
  status = 301
  force = true

