backend:
  name: git-gateway
  branch: main  # Dein GitHub-Branch, normalerweise "main"

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"  # Der Ordner, in dem die Seiten gespeichert werden
    create: true
    slug: "{{slug}}"  # Der Slug (URL) für jede Seite
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "text" }
